modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/Arborsm/GTM-EMI-Compat/issues"

[[mods]]
modId = "gtm_emi_compat"
version = "${version}"
displayName = "GTM EMI Compat"
logoFile = "icon.png"
authors = "Arbor, Ph"
description = '''
Rewrite EMI Compat of GTM
'''

[[dependencies.gtm_emi_compat]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtm_emi_compat]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtm_emi_compat]]
modId = "gtceu"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.gtm_emi_compat]]
modId = "emi"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"